version: '3'
services:
  app:
    container_name: api-skeleton
    restart: always
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    image: 'postgres:14.5-alpine'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=main
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
