version: '3'
services:
  app:
    container_name: api-skeleton
    restart: always
    environment:
      - GIT_WORK_TREE=/usr/src/app
      - GIT_DIR=/usr/src/app/.git
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3001"
